config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/register', to: 'devise/registrations#new'
    get '/login', to: 'devise/sessions#new'
    get '/logout', to: 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :users, only: [:show]

  resources :lists, only: [:new, :create, :show, :edit, :index, :update] do
    get '/close', to: 'lists#close_list'
  end

  resources :ballots, only: [:new, :create, :show] do
    resources :votes, only: [:create, :destroy, :update]
    post '/discog_search', to: 'ballots#discog_search'
  end

  post '/ballots/:ballot_id/sort_votes', to: 'ballots#sort_votes'
  post '/album_info', to: 'ballots#album_info'

end

app/models/list.rb
class List < ApplicationRecord
  include BallotsHelper

  belongs_to :owner, class_name: User
  has_many :ballots
  has_many :voters, through: :ballots, class_name: User
  has_many :votes, through: :ballots

  validates :title, presence: true
  validates :maximum, presence: true
  validates :minimum, presence: true

  def list_to_json
    json = {
      id: self.id,
      title: self.title,
      voters: self.get_list_voters,
      results: self.get_list_results
    }
  end

  def get_list_results
    album_points = self.tally_results
    album_points.inject([]) do |memo, (album_id, points)|
      memo << {
        album_data: Discog.find_by(album_id: album_id),
        points: points,
        voters: self.get_album_voters(album_id),
        reviews: self.get_album_reviews(album_id)
      }
    end
  end

  def tally_results
    self.votes.select {|vote| vote.ballot.votes.length >= self.minimum }.select {|vote| vote.rank <= self.maximum}.each_with_object(Hash.new(0)) do |vote, memo|
      memo[vote.album_id] += ((self.maximum + 1) - vote.rank)
    end
  end

  def get_list_voters
    self.voters.inject([]) do |memo, voter|
      ballot = voter.ballots.find_by(list: self)
      memo << { id: voter.id, ballot_id: ballot.id, username: voter.username }
    end
  end

  def get_album_voters(id)
    self.voters.inject([]) do |memo, voter|
      ballot = voter.ballots.find_by(list: self)
      if ballot.votes.pluck(:album_id).include?(id)
        memo << {id: voter.id, username: voter.username, ballot_id: ballot.id}
      end
      memo
    end
  end

  def get_album_reviews(id)
    reviews = self.votes.select {|vote| vote.album_id == id && vote.review != "" }
    reviews.inject([]) do |memo, vote|
      memo << {review: vote.review, username: vote.ballot.voter.username, ballot_id: vote.ballot.id}
    end
  end

  def reviews
    reviews = self.votes.select { |vote| vote.review != "" }
    new_reviews = reviews.inject([]) do |memo, vote|
      memo << {review: vote.review, created_at: vote.updated_at, username: vote.ballot.voter.username, ballot_id: vote.ballot.id, artist: vote.discog.artist, title: vote.discog.title }
    end
    new_reviews
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @open_lists = List.where(open: true)
    @closed_lists = List.where(open: false)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.owner = current_user

    if @list.save
      redirect_to @list
    else
      render 'new'
    end
  end

  def show
    @list = List.find(params[:id])
    if !@list.open
      @list_data = @list.list_to_json
    end
  end

  def edit
    @list = List.find(params[:id])
    redirect_to @list unless current_user == @list.owner
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to @list
  end

  def close_list
    @list = List.find(params[:list_id])
    if @list.owner == current_user
      @list.open = false
      @list.save
      redirect_to @list
    else
      redirect_to @list
    end
  end

  protected

    def list_params
      params.require(:list).permit(:title, :maximum, :minimum, :notes)
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label "Minimum number of albums" %>
  <%= f.number_field :minimum %>

  <%= f.label "Maximum number of albums" %>
  <%= f.number_field :maximum %>

  <%= f.label "Guidelines" %><br />
  <%= f.text_area(:notes, cols: 65, rows: 10) %>

  <%= f.submit %>

<% end %>

app/views/lists/_options.html.erb
<div class="options">
  <b>List options:</b>
  <ul>
  <li><%= link_to "Edit this list", edit_list_path(@list) %></li>
  <li><%= link_to "Close voting", list_close_path(@list) %></li>
  </ul>
</div>

app/views/lists/edit.html.erb
<% if current_user == @list.owner %>
  <h1>Editing <%= @list.title %></h1>

  <%= render 'form' %>

  <p><%= link_to "Back to list...", @list %>
<% else %>
  <h3>You are not authorized to view this page...</h3>
<% end %>

app/views/lists/index.html.erb
<% if !@open_lists.empty? %>
  <h1>Open Lists</h1>

  <div class="lists-container">
    <% @open_lists.each do |list| %>
      <div class="list-link">
        <%= link_to list.title, list %>, created by <%= list.owner.username %>
      </div>
    <% end %>
  </div>
<% end %>

<% if !@closed_lists.empty? %>
  <h1>Closed Lists</h1>

  <div class="lists-container">
    <% @closed_lists.each do |list| %>
      <div class="list-link">
        <%= link_to list.title, list %>, created by <%= list.owner.username %>
      </div>
    <% end %>
  </div>
<% end %>

<% if user_signed_in? %>
  <div class="new-list">
    <%= link_to "...Open a new list", new_list_url %>
  </div>
<% end %>

app/views/lists/new.html.erb
<h1>Create a new list...</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<div class="list-page">
  <h1><%= @list.title %></h1>
  <div class="row">

    <div class="col-md-3">
      <p><b>Created by:</b> <%= link_to @list.owner.username, user_path(@list.owner) %></p>

      <% if @list.notes != "" %>
        <p class="sidebar-title">Guidelines:</p>
        <p><%= @list.notes %></p>
      <% end %>

      <% if @list.owner == current_user && @list.open %>
        <%= render 'options' %>
      <% end %>

      <% if @list.voters.include?(current_user) %>
        <% @ballot = @list.ballots.find_by(voter: current_user) %>
        <p><%= link_to "Adjust your ballot", @ballot %></p>

      <% elsif user_signed_in? %>
        <form class="add-ballot-btn" action="/ballots" method="post">
          <input type="hidden" name="list_id" value="<%= @list.id %>">
          <input type="submit" value="Create your ballot">
        </form>
      <% else %>
        <p><%= link_to "Log in to contribute", '/login' %></p>
      <% end %>

      <p class="sidebar-title">Contributions:</p>
      <p>
      <% @list.voters.each do |voter| %>
        <div><a href="/ballots/<%= voter.ballots.find_by(list: @list).id %>"><%= voter.username %></a></div>
      <% end %>
      </p>
    </div>

    <div class="col-md-9">
      <% if @list.open %>
        <h2>Voting for this list is still open. Check back later to see the results.</h2>
        <%= react_component "LatestReviews", reviews: @list.reviews.sort_by {|review| review[:created_at]}.reverse[0..25] %>
      <% else %>
        <%= react_component "ListResults", results: @list_data[:results].sort_by {|result| result[:points]}.reverse %>
      <% end %>
    </div>

  </div>
</div>