config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/register', to: 'devise/registrations#new'
    get '/login', to: 'devise/sessions#new'
    get '/logout', to: 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :users, only: [:show]

  resources :lists, only: [:new, :create, :show, :edit, :index, :update] do
    get '/close', to: 'lists#close_list'
  end

  resources :ballots, only: [:new, :create, :show] do
    resources :votes, only: [:create, :destroy, :update]
    post '/discog_search', to: 'ballots#discog_search'
  end

  post '/ballots/:ballot_id/sort_votes', to: 'ballots#sort_votes'
  post '/album_info', to: 'ballots#album_info'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :owned_lists, class_name: List, foreign_key: 'owner_id'
  has_many :ballots, foreign_key: 'voter_id'
  has_many :lists_voted_on, through: :ballots, source: :list
  has_many :votes, through: :ballots

  validates :username, presence: true
  validates :username, uniqueness: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
  end

end

app/views/users/show.html.erb
<% if @user.owned_lists.any? %>
  <h3>Lists <%= @user.username.capitalize %> started</h3>
  <ul>
    <% @user.owned_lists.each do |list| %>
      <li><%= link_to list.title, list_path(list) %></li>
    <% end %>
  </ul>
<% end %>

<% if @user.ballots.any? %>
  <h3><%= @user.username.capitalize %>'s Contributions</h3>
  <ul>
    <% @user.ballots.each do |ballot| %>
      <li><%= link_to ballot.list.title, ballot_path(ballot) %></li>
    <% end %>
  </ul>
<% end %>